<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="9CQX9K3" name="com.herokuapp.theinternet.alertstests.AlertsTests" tests="3" failures="1" timestamp="13 May 2022 14:27:13 GMT" time="29.465" errors="0">
  <testcase name="jsPromptTest" time="10.256" classname="com.herokuapp.theinternet.alertstests.AlertsTests"/>
  <testcase name="jsAlertTest" time="9.706" classname="com.herokuapp.theinternet.alertstests.AlertsTests">
    <failure type="java.lang.AssertionError" message="result is not expected. 
Should be &#039;You successfuly clicked an alert&#039;, but it is &#039;You successfully clicked an alert&#039; expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: result is not expected. 
Should be 'You successfuly clicked an alert', but it is 'You successfully clicked an alert' expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.herokuapp.theinternet.alertstests.AlertsTests.jsAlertTest(AlertsTests.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
]]>
    </failure>
  </testcase> <!-- jsAlertTest -->
  <testcase name="jsDismissTest" time="9.503" classname="com.herokuapp.theinternet.alertstests.AlertsTests"/>
</testsuite> <!-- com.herokuapp.theinternet.alertstests.AlertsTests -->
